keys:
  - &hosts:
    - &elmira age1r3gh0cyefzalugcqd3jvnxjzkhv70ph2ag7438vuvk5xlx7rryrs7pvfpe
    - &marlon age1l6rfsztcxez94nl5nwyjlpr0gqnsngzwr0aqrtctp045j9nj8deq0y0kww 
    - &vic age1fu6wm42w4ke6ecwhwwqv7arfgn5spt7yzkj5rcassa0l0vyqgg4snyvv7m

creation_rules:
  - path_regex: hosts/marlon/secrets.yaml$
    key_groups:
      - age:
        - *elmira
        - *marlon
  - path_regex: hosts/vic/secrets.yaml$
    key_groups:
      - age:
        - *elmira
        - *vic

